{{- if eq .Values.persistentVolume.enabled "true" }}
{{- range .Values.persistentVolume.volume }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}
spec:
  storageClassName: {{ .storageClassName }}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .storageClassName }}
  hostPath:
    path: {{ .hostPath }}
{{- end }}
{{- end }}
