{{- if eq .Values.image.privateRepo.enabled true }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerPullSecret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ .Values.image.pullSecret }}
{{- end }}
